version: '3.8'
services:
  app:
    image: user-auth-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - dbUser-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbUser-container:3306/users?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Acse11..
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: true
      SPRING_FLYWAY_USER: root
      SPRING_FLYWAY_PASSWORD: Acse11..
    networks:
      - rcpnetwork

  dbUser-container:
    image: mysql:8.0
    container_name: dbUser-container
    environment:
      MYSQL_ROOT_PASSWORD: Acse11..
      MYSQL_DATABASE: users
    ports:
      - "3307:3306"
    networks:
      - rcpnetwork

networks:
  rcpnetwork:
    driver: bridge
